name: Deb Canary

on:
  # This workflow will run from the release-automation.yaml automation on each merge
  workflow_dispatch:
    inputs:
      ref_name:
        required: true
        type: string
  workflow_call:
    inputs:
      ref_name:
        required: true
        type: string

  # This workflow will run every 5 min
  schedule:
    - cron: '*/10 * * * *'
  
  # This workflow will run when the workflow file is updated
  pull_request:
    paths:
      - '.github/workflows/canary-deb.yaml'
      - 'scripts/canary-deb.sh'
  
jobs:
  canary-deb:
    name: Test Finch APT repo health
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout canary script
        uses: actions/checkout@v6.0.2
        with:
          sparse-checkout: |
            scripts/canary-deb.sh
      - name: Run canary script with retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 2
          max_attempts: 3
          retry_wait_seconds: 30
          command: ./scripts/canary-deb.sh
