name: get-output-arch
on:
  workflow_call:
    inputs:
      arch:
        type: string
        required: true

jobs:
  get-output-arch:
    outputs:
      arch: ${{ steps.output-arch.arch }}
    runs-on: ubuntu-latest
    steps:
      - name: 'get output arch'
        id: output-arch
        run: |
          shopt -s nocasematch
          if [[ ${{ inputs.arch }} == "amd64" ]]; then
            echo "arch=x86_64" >> "$GITHUB_OUTPUT"
          elif [[ ${{ inputs.arch }} == "arm64" ]]; then
            echo "arch=aarch64" >> "$GITHUB_OUTPUT"
          fi
